name: PR

on: 
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: 
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        node_version: ['10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v2.0.0
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1.1.0
      with:
        version: ${{ matrix.node_version }}

    - name: Yarn
      run: yarn
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test
