name: PR

on: 
  issue_comment:
    types: [created]
  pull_request:
    branches: 
      - master

jobs:
  build:
    if: github.event_name != 'issue_comment' || (github.event.pull_request != null && github.event.comment.body == '/build')

    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        node_version: ['10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2.0.0
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1.1.0
      with:
        version: ${{ matrix.node_version }}
    - name: Build & Test
      run: |
        yarn
        yarn build
        yarn test
